default_agent: calculator_agent
agents:
  calculator_agent:
    name: calculator_agent
    entrypoint: /Users/ychchen/warren_ws/Nexus-AI/agents/generated_agents/calculator_agent/calculator_agent.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::034362076319:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-0b01dcd18d
      execution_role_auto_create: false
      account: 034362076319
      region: us-west-2
      ecr_repository: 034362076319.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-calculator_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: calculator_agent-7ZZGQN6uML
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:034362076319:runtime/calculator_agent-7ZZGQN6uML
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-calculator_agent-builder
      execution_role: arn:aws:iam::034362076319:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-0b01dcd18d
      source_bucket: bedrock-agentcore-codebuild-sources-034362076319-us-west-2
    authorizer_configuration: null
    oauth_configuration: null
