default_agent: cat_breed_identifier
agents:
  cat_breed_identifier:
    name: cat_breed_identifier
    entrypoint: /Users/ychchen/warren_ws/Nexus-AI/agents/generated_agents/cat_breed_identifier/cat_breed_identifier.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::034362076319:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-17581a4025
      execution_role_auto_create: false
      account: 034362076319
      region: us-west-2
      ecr_repository: 034362076319.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-cat_breed_identifier
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: cat_breed_identifier-BlkS5m4IKs
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:034362076319:runtime/cat_breed_identifier-BlkS5m4IKs
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-cat_breed_identifier-builder
      execution_role: arn:aws:iam::034362076319:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-17581a4025
      source_bucket: bedrock-agentcore-codebuild-sources-034362076319-us-west-2
    authorizer_configuration: null
    oauth_configuration: null
