default_agent: fda_data_query_agent
agents:
  fda_data_query_agent:
    name: fda_data_query_agent
    entrypoint: /Users/qangz/Downloads/99.Project/Nexus-AI/agents/generated_agents/fda_data_query_agent/fda_data_query_agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: arn:aws:iam::238090515572:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-5a6b5afc6b
      execution_role_auto_create: false
      account: '238090515572'
      region: us-west-2
      ecr_repository: 238090515572.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-fda_data_query_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: fda_data_query_agent-KpTz3j6D0R
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:238090515572:runtime/fda_data_query_agent-KpTz3j6D0R
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-fda_data_query_agent-builder
      execution_role: arn:aws:iam::238090515572:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-5a6b5afc6b
      source_bucket: bedrock-agentcore-codebuild-sources-238090515572-us-west-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
