default_agent: text_to_poetry_agent
agents:
  text_to_poetry_agent:
    name: text_to_poetry_agent
    entrypoint: /Users/ychchen/warren_ws/Nexus-AI/agents/generated_agents/text_to_poetry_agent/text_to_poetry_agent.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::034362076319:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-04ee910c2f
      execution_role_auto_create: false
      account: 034362076319
      region: us-west-2
      ecr_repository: 034362076319.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-text_to_poetry_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: text_to_poetry_agent-RRnrCfAQge
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:034362076319:runtime/text_to_poetry_agent-RRnrCfAQge
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-text_to_poetry_agent-builder
      execution_role: arn:aws:iam::034362076319:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-04ee910c2f
      source_bucket: bedrock-agentcore-codebuild-sources-034362076319-us-west-2
    authorizer_configuration: null
    oauth_configuration: null
