default_agent: sports_team_match_predictor
agents:
  sports_team_match_predictor:
    name: sports_team_match_predictor
    entrypoint: /Users/ychchen/warren_ws/Nexus-AI/agents/generated_agents/sports_team_match_predictor/sports_team_match_predictor.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::034362076319:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-82a61d14d4
      execution_role_auto_create: false
      account: 034362076319
      region: us-east-1
      ecr_repository: 034362076319.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-sports_team_match_predictor
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    authorizer_configuration: null
    oauth_configuration: null
