project:
  created_date: '2025-09-23T17:42:02.095699+00:00'
  description: 一个专为临床开发人员设计的智能检索Agent，能够自动检索clinicaltrials.gov的数据，支持多次深度检索并整合分析结果，确保检索内容全面、完整且正确。
  name: clinicaltrials_search_agent
  updated_date: '2025-09-23T17:42:06.459900+00:00'
  version: 1.0.0
