default_agent: stock_information_collector
agents:
  stock_information_collector:
    name: stock_information_collector
    entrypoint: /Users/ychchen/warren_ws/Nexus-AI/agents/generated_agents/stock_information_collector/stock_information_collector.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::034362076319:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-680cbaf87d
      execution_role_auto_create: false
      account: 034362076319
      region: us-west-2
      ecr_repository: 034362076319.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-stock_information_collector
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: stock_information_collector-sSwXs07p9A
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:034362076319:runtime/stock_information_collector-sSwXs07p9A
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-stock_information_collector-builder
      execution_role: arn:aws:iam::034362076319:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-680cbaf87d
      source_bucket: bedrock-agentcore-codebuild-sources-034362076319-us-west-2
    authorizer_configuration: null
    oauth_configuration: null
