default_agent: fitness_advisor_agent
agents:
  fitness_advisor_agent:
    name: fitness_advisor_agent
    entrypoint: /Users/ychchen/warren_ws/Nexus-AI/agents/generated_agents/fitness_advisor/fitness_advisor_agent.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::034362076319:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-fd2a53e8fc
      execution_role_auto_create: false
      account: 034362076319
      region: us-west-2
      ecr_repository: 034362076319.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-fitness_advisor_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: fitness_advisor_agent-bUADlV3mEM
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:034362076319:runtime/fitness_advisor_agent-bUADlV3mEM
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-fitness_advisor_agent-builder
      execution_role: arn:aws:iam::034362076319:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-fd2a53e8fc
      source_bucket: bedrock-agentcore-codebuild-sources-034362076319-us-west-2
    authorizer_configuration: null
    oauth_configuration: null
