# Agent模板配置文件
# 用于管理所有可用的Agent模板，包含描述信息和路径

templates:
  # 单Agent模板 - 本地工具
  single_agent_with_local_tool:
    name: "单Agent本地工具模板"
    description: "适用于需要自定义本地工具的单一Agent场景，支持自定义工具函数和Bedrock模型集成"
    dependencies:
      - "strands"
      - "strands_tools"
      - "bedrock_agentcore"
    path: "templates/agents/single_agent_with_local_tool_template.py"
    tags:
      - "single_agent"
      - "strands_tools"

  # 单Agent模板 - MCP SSE
  single_agent_with_mcp_sse:
    name: "单Agent MCP SSE模板"
    description: "适用于需要连接MCP服务器并使用SSE传输的单一Agent场景"
    dependencies:
      - "strands"
      - "mcp"
    path: "templates/agents/single_agent_with_mcp_sse.py"
    tags:
      - "single_agent"
      - "mcp_sse"

  # 单Agent模板 - MCP StreamableHTTP
  single_agent_with_mcp_streamablehttp:
    name: "单Agent MCP StreamableHTTP模板"
    description: "适用于需要连接MCP服务器并使用StreamableHTTP传输的单一Agent场景"
    dependencies:
      - "strands"
      - "mcp"
    path: "templates/agents/single_agent_with_mcp_streamablehttp.py"
    tags:
      - "single_agent"
      - "mcp_streamablehttp"

  # 多Agent模板 - Agent作为工具
  multi_agents_with_agent_as_tool:
    name: "多Agent协作模板"
    description: "适用于需要多个专业Agent协作的复杂场景，支持Agent间调用和任务路由"
    dependencies:
      - "strands"
      - "strands_tools"
    path: "templates/agents/multi_agents_with_agent_as_tool.py"
    tags:
      - "multi_agent"
      - "strands_tools" 