# Agent模板配置文件
# 用于管理所有可用的Agent模板，包含描述信息和路径

templates:
  # 单Agent模板 - 本地工具
  single_agent_with_local_tool:
    name: "单Agent本地工具模板"
    description: "集成Bedrock AgentCore的单Agent模板，支持自定义工具函数、计算器工具和Bedrock Claude模型。包含完整的应用入口点配置，适用于需要本地工具扩展和AWS Bedrock集成的生产环境"
    dependencies:
      - "strands"
      - "strands_tools"
      - "bedrock_agentcore"
    path: "agents/template_agents/single_agent/template_requirements_analyzer.py"
    tags:
      - "single_agent"
      - "strands_tools"
      - "bedrock"
      - "production"