# Agent模板配置文件
# 用于管理所有可用的Agent模板，包含描述信息和路径

templates:
  # 需求分析师模板 - 文档处理专家
  requirements_analyzer:
    name: "需求分析文档生成器"
    description: "单Agent模板，专业的需求分析师，将自然语言需求转换为标准化JSON格式需求文档。集成文件读取、时间获取、AWS服务等系统工具，支持业务需求分析、用户故事生成、验收标准定义。输出结构化需求文档，适用于软件开发、产品设计、项目管理等场景"
    agent_dependencies: []
    tools_dependencies:
      - "strands_tools/file_read"
      - "strands_tools/current_time"
      - "strands_tools/use_aws"
    path: "agents/template_agents/single_agent/requirements_analyzer.py"
    prompt_template: "prompts/template_prompts/template_requirements_analyzer"
    tags:
      - "single_agent"
      - "system_tools"
      - "document_processing"
      - "requirements_analysis"
      - "json_output"
      - "aws_integration"
      - "structured_output"

  # 文档处理Agent模板 - 文本分析专家
  document_processor_agent:
    name: "智能文档处理器"
    description: "单Agent模板，专业的文档处理专家，能够处理各种格式的文档并进行智能分析。集成文件读取、文本处理、格式转换等工具，支持文档解析、内容提取、格式转换、文本分析等功能。适用于文档管理、内容分析、格式转换等场景"
    agent_dependencies: []
    tools_dependencies:
      - "strands_tools/file_read"
      - "strands_tools/file_write"
      - "strands_tools/current_time"
      - "template_tools/common/text_processor/text_analyzer"
      - "template_tools/common/text_processor/format_converter"
    path: "agents/template_agents/single_agent/document_processor_agent.py"
    prompt_template: "prompts/template_prompts/document_processor_agent"
    tags:
      - "single_agent"
      - "document_processing"
      - "text_analysis"
      - "format_conversion"
      - "content_extraction"
      - "file_operations"

  # 数据分析Agent模板 - 数据处理专家
  data_analyzer_agent:
    name: "智能数据分析师"
    description: "单Agent模板，专业的数据分析专家，能够处理各种数据格式并进行统计分析。集成数据读取、清洗、分析、可视化等工具，支持数据预处理、统计分析、图表生成、报告输出等功能。适用于数据分析、报表生成、数据可视化等场景"
    agent_dependencies: []
    tools_dependencies:
      - "strands_tools/file_read"
      - "strands_tools/file_write"
      - "strands_tools/current_time"
      - "template_tools/data/data_processor/data_cleaner"
      - "template_tools/data/data_processor/statistical_analyzer"
      - "template_tools/data/visualization/chart_generator"
    path: "agents/template_agents/single_agent/data_analyzer_agent.py"
    prompt_template: "prompts/template_prompts/data_analyzer_agent"
    tags:
      - "single_agent"
      - "data_analysis"
      - "statistical_analysis"
      - "data_visualization"
      - "report_generation"
      - "data_processing"

  # API集成Agent模板 - 接口调用专家
  api_integration_agent:
    name: "API集成专家"
    description: "单Agent模板，专业的API集成专家，能够与各种外部服务进行集成。集成HTTP客户端、认证管理、数据转换等工具，支持API调用、数据同步、格式转换、错误处理等功能。适用于系统集成、数据同步、服务调用等场景"
    agent_dependencies: []
    tools_dependencies:
      - "strands_tools/current_time"
      - "template_tools/network/http_client/api_client"
      - "template_tools/network/http_client/auth_manager"
      - "template_tools/common/data_converter/json_converter"
      - "template_tools/common/data_converter/xml_converter"
    path: "agents/template_agents/single_agent/api_integration_agent.py"
    prompt_template: "prompts/template_prompts/api_integration_agent"
    tags:
      - "single_agent"
      - "api_integration"
      - "http_client"
      - "data_sync"
      - "service_integration"
      - "external_services"

  # 内容生成Agent模板 - 创意生成专家
  content_generator_agent:
    name: "智能内容生成器"
    description: "单Agent模板，专业的内容生成专家，能够根据需求生成各种类型的内容。集成文本生成、模板管理、内容优化等工具，支持文章写作、报告生成、创意内容、营销文案等功能。适用于内容创作、文案生成、报告编写等场景"
    agent_dependencies: []
    tools_dependencies:
      - "strands_tools/file_write"
      - "strands_tools/current_time"
      - "template_tools/common/content_generator/text_generator"
      - "template_tools/common/content_generator/template_manager"
      - "template_tools/common/content_generator/content_optimizer"
    path: "agents/template_agents/single_agent/content_generator_agent.py"
    prompt_template: "prompts/template_prompts/content_generator_agent"
    tags:
      - "single_agent"
      - "content_generation"
      - "creative_writing"
      - "report_generation"
      - "marketing_content"
      - "text_creation"

  # 深度研究Agent模板 - 研究分析专家
  deep_research_agent:
    name: "深度研究专家"
    description: "单Agent模板，专业的深度研究专家，能够进行真实的互联网查询和信息收集、分析和综合。集成真实网络搜索、数据分析、报告生成、趋势预测等工具，支持真实多源信息收集、深度分析、知识综合、报告生成、趋势预测等功能。适用于市场研究、技术分析、行业调研、学术研究等场景，所有分析都基于真实互联网数据"
    agent_dependencies: []
    tools_dependencies:
      - "strands_tools/http_request"
      - "strands_tools/rss"
      - "strands_tools/file_read"
      - "strands_tools/file_write"
      - "strands_tools/current_time"
      - "template_tools/common/research_tools/information_collector"
      - "template_tools/common/research_tools/web_search_enhanced"
      - "template_tools/common/research_tools/data_analyzer"
      - "template_tools/common/research_tools/report_generator"
      - "template_tools/common/research_tools/trend_predictor"
    path: "agents/template_agents/single_agent/deep_research_agent.py"
    prompt_template: "prompts/template_prompts/deep_research_agent"
    tags:
      - "single_agent"
      - "research_analysis"
      - "information_collection"
      - "data_analysis"
      - "report_generation"
      - "trend_prediction"
      - "market_research"
      - "academic_research"
      - "real_data"
      - "web_search"

  # 多模态内容分析Agent模板 - 多模态分析专家
  multimodal_analyzer_agent:
    name: "多模态内容分析专家"
    description: "单Agent模板，专业的多模态内容分析专家，能够处理各种类型的文件（图片、文档、文本等）并进行智能分析和问答。集成multimodal_content_parser工具、文件读取、时间获取等系统工具，支持多格式文件解析、智能内容识别、多轮对话交互、问题导向分析等功能。适用于文档分析、图片识别、内容理解、智能问答等场景"
    agent_dependencies: []
    tools_dependencies:
      - "system_tools/multimodal_content_parser/parse_multimodal_content_from_path"
      - "system_tools/multimodal_content_parser/get_supported_formats"
      - "strands_tools/file_read"
      - "strands_tools/current_time"
    path: "agents/system_agents/multimodal_analysis/multimodal_analyzer_agent.py"
    prompt_template: "prompts/system_agents_prompts/multimodal_analysis/multimodal_analyzer_agent"
    tags:
      - "single_agent"
      - "multimodal_analysis"
      - "content_analysis"
      - "file_processing"
      - "conversation"
      - "question_answering"
      - "image_analysis"
      - "document_analysis"
      - "intelligent_qa"
      - "multimodal_processing"

  # PDF内容提取Agent模板 - PDF处理专家
  pdf_extractor_agent:
    name: "PDF内容提取专家"
    description: "单Agent模板，专业的PDF内容提取专家，能够处理PDF文件，将其转换为图片，调用多模态Agent提取文本内容，并生成TXT文件，支持断点续传功能。集成PDF处理工具、多模态分析、状态管理等工具，支持PDF转图片、文本提取、内容合并、断点续传等功能。适用于文档处理、内容提取、格式转换等场景"
    agent_dependencies: []
    tools_dependencies:
      - "generated_tools/pdf_content_extractor/pdf_processing_tools/pdf_to_images"
      - "generated_tools/pdf_content_extractor/pdf_processing_tools/manage_processing_state"
      - "generated_tools/pdf_content_extractor/pdf_processing_tools/merge_text_content"
      - "generated_tools/pdf_content_extractor/pdf_processing_tools/initialize_pdf_extraction"
      - "generated_tools/pdf_content_extractor/pdf_processing_tools/cleanup_extraction_files"
      - "strands_tools/file_read"
      - "strands_tools/file_write"
      - "strands_tools/current_time"
    path: "agents/template_agents/single_agent/pdf_extractor_agent.py"
    prompt_template: "prompts/generated_agents_prompts/pdf_content_extractor/pdf_extractor_agent"
    tags:
      - "single_agent"
      - "pdf_processing"
      - "content_extraction"
      - "multimodal_analysis"
      - "text_extraction"
      - "document_processing"
      - "checkpoint_resume"
      - "file_conversion"
      - "batch_processing"

  # HTML2PPTX转换Agent模板 - 文档转换专家
  html2pptx_agent:
    name: "HTML2PPTX转换专家"
    description: "单Agent模板，专业的HTML到PPTX转换专家，能够将HTML文档转换为PPTX格式的演示文稿，保留原始文档的结构、样式、图片和语义内容，支持自定义模板，并能处理任意复杂度的HTML文档。集成HTML解析、PPT生成、图片处理、缓存管理等工具，支持文档解析、样式映射、布局优化、模板应用等功能。适用于文档转换、演示文稿生成、格式转换等场景"
    agent_dependencies: []
    tools_dependencies:
      - "strands_tools/file_read"
      - "strands_tools/file_write"
      - "strands_tools/current_time"
      - "strands_tools/calculator"
      - "generated_tools/html2pptx/html_parser/parse_html"
      - "generated_tools/html2pptx/html_parser/extract_elements"
      - "generated_tools/html2pptx/html_parser/extract_text_content"
      - "generated_tools/html2pptx/html_parser/extract_images"
      - "generated_tools/html2pptx/html_parser/extract_tables"
      - "generated_tools/html2pptx/html_parser/extract_links"
      - "generated_tools/html2pptx/html_parser/analyze_document_structure"
      - "generated_tools/html2pptx/semantic_analyzer/analyze_document_structure"
      - "generated_tools/html2pptx/semantic_analyzer/identify_key_topics"
      - "generated_tools/html2pptx/semantic_analyzer/extract_hierarchical_structure"
      - "generated_tools/html2pptx/semantic_analyzer/analyze_content_importance"
      - "generated_tools/html2pptx/semantic_analyzer/extract_key_content"
      - "generated_tools/html2pptx/semantic_analyzer/suggest_slide_structure"
      - "generated_tools/html2pptx/semantic_analyzer/summarize_content"
      - "generated_tools/html2pptx/style_mapper/analyze_document_theme"
      - "generated_tools/html2pptx/style_mapper/extract_html_styles"
      - "generated_tools/html2pptx/style_mapper/map_color_scheme"
      - "generated_tools/html2pptx/style_mapper/map_font_scheme"
      - "generated_tools/html2pptx/style_mapper/map_html_styles_to_ppt"
      - "generated_tools/html2pptx/style_mapper/map_text_style_to_ppt"
      - "generated_tools/html2pptx/style_mapper/get_element_box_model"
      - "generated_tools/html2pptx/pptx_generator/create_presentation"
      - "generated_tools/html2pptx/pptx_generator/add_slide"
      - "generated_tools/html2pptx/pptx_generator/add_text"
      - "generated_tools/html2pptx/pptx_generator/add_image"
      - "generated_tools/html2pptx/pptx_generator/add_table"
      - "generated_tools/html2pptx/pptx_generator/add_shape"
      - "generated_tools/html2pptx/pptx_generator/get_presentation_info"
      - "generated_tools/html2pptx/layout_optimizer/optimize_slide_layout"
      - "generated_tools/html2pptx/layout_optimizer/optimize_image_placement"
      - "generated_tools/html2pptx/layout_optimizer/optimize_table_layout"
      - "generated_tools/html2pptx/layout_optimizer/optimize_visual_hierarchy"
      - "generated_tools/html2pptx/layout_optimizer/suggest_content_distribution"
      - "generated_tools/html2pptx/layout_optimizer/create_balanced_composition"
      - "generated_tools/html2pptx/layout_optimizer/calculate_text_box_size"
      - "generated_tools/html2pptx/image_processor/download_image"
      - "generated_tools/html2pptx/image_processor/resize_image"
      - "generated_tools/html2pptx/image_processor/optimize_image"
      - "generated_tools/html2pptx/image_processor/crop_image"
      - "generated_tools/html2pptx/image_processor/convert_image_format"
      - "generated_tools/html2pptx/image_processor/enhance_image"
      - "generated_tools/html2pptx/image_processor/get_image_info"
      - "generated_tools/html2pptx/cache_manager/initialize_cache"
      - "generated_tools/html2pptx/cache_manager/cached_operation"
      - "generated_tools/html2pptx/cache_manager/retrieve_cached_item"
      - "generated_tools/html2pptx/cache_manager/cache_item"
      - "generated_tools/html2pptx/cache_manager/delete_cached_item"
      - "generated_tools/html2pptx/cache_manager/get_cache_info"
      - "generated_tools/html2pptx/cache_manager/clear_cache"
    path: "agents/template_agents/single_agent/html2pptx_agent.py"
    prompt_template: "prompts/generated_agents_prompts/html2pptx/html2pptx_agent"
    tags:
      - "single_agent"
      - "document_conversion"
      - "html_processing"
      - "pptx_generation"
      - "semantic_analysis"
      - "style_mapping"
      - "layout_optimization"
      - "image_processing"
      - "cache_management"
      - "template_support"
