default_agent: file_summarizer
agents:
  file_summarizer:
    name: file_summarizer
    entrypoint: /Users/ychchen/warren_ws/Nexus-AI/agents/generated_agents/file_summary_agent/file_summarizer.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::034362076319:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-dc41af4874
      execution_role_auto_create: false
      account: 034362076319
      region: us-west-2
      ecr_repository: 034362076319.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-file_summarizer
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: file_summarizer-20694WEZRC
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:034362076319:runtime/file_summarizer-20694WEZRC
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-file_summarizer-builder
      execution_role: arn:aws:iam::034362076319:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-dc41af4874
      source_bucket: bedrock-agentcore-codebuild-sources-034362076319-us-west-2
    authorizer_configuration: null
    oauth_configuration: null
