default_agent: openfda_data_agent
agents:
  openfda_data_agent:
    name: openfda_data_agent
    entrypoint: /Users/ychchen/warren_ws/Nexus-AI/agents/generated_agents/openfda_data_agent/openfda_data_agent.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::034362076319:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-788a954d59
      execution_role_auto_create: false
      account: 034362076319
      region: us-west-2
      ecr_repository: 034362076319.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-openfda_data_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: openfda_data_agent-zQTrB6Fo1Z
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:034362076319:runtime/openfda_data_agent-zQTrB6Fo1Z
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-openfda_data_agent-builder
      execution_role: arn:aws:iam::034362076319:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-788a954d59
      source_bucket: bedrock-agentcore-codebuild-sources-034362076319-us-west-2
    authorizer_configuration: null
    oauth_configuration: null
